In [32]:
import numpy as np
import matplotlib.pyplot as plt
from qutip import basis, qeye, sigmax, sigmay, sigmaz, tensor
from qutip import *

In [35]:
N = 3 #Number of spins

gs = tensor(basis(2,0),basis(2,0),basis(2,0)) # There are 2 (up or down) states a spin can have. So total dimension of hilbert space in 2^3. Here all spins are in
                   # 0 (up) state

In [37]:
gs

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [7]:
#Hamiltonian for subsystem A
J = 1

sx1 = tensor(sigmax(),qeye(2),qeye(2))
sy1 = tensor(sigmay(),qeye(2),qeye(2))
sz1 = tensor(sigmaz(),qeye(2),qeye(2))

H_a = J*(sx1+sy1+sz1)

In [8]:
#Hamiltonian for subsystem B

sx3 = tensor(qeye(2),qeye(2),sigmax())
sy3 = tensor(qeye(2),qeye(2),sigmay())
sz3 = tensor(qeye(2),qeye(2),sigmay())

H_b = J*(sx3+sy3+sz3)

In [20]:
#Hamiltonian for subsytem C
T = 0.5
sx2 = tensor(qeye(2),sigmax(),qeye(2))
sz2 = tensor(qeye(2),sigmaz(),qeye(2))

H_c = T*1j*sz2 + J*sx2

In [25]:
sx2

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]

In [12]:
#Interactions

sx_ac = tensor(sigmax(),sigmax(),qeye(2))
sy_ac = tensor(sigmay(),sigmay(),qeye(2))
sz_ac = tensor(sigmaz(),sigmaz(),qeye(2))

sx_bc = tensor(qeye(2),sigmax(),sigmax())
sy_bc = tensor(qeye(2),sigmay(),sigmay())
sz_bc = tensor(qeye(2),sigmaz(),sigmaz())

sx_ab = tensor(sigmax(),qeye(2),sigmax())
sy_ab = tensor(sigmay(),qeye(2),sigmay())
sz_ab = tensor(sigmaz(),qeye(2),sigmaz())

D = 0.5

H_ac = J*(sx_ac + sy_ac) + D*(sz_ac)
H_bc = J*(sx_bc + sy_bc) + D*(sz_bc)
H_ab = J*(sx_ab + sy_ab) + D*(sz_bc)

In [14]:
H

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.+0.j  0.+0.j  1.+0.5j 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j ]
 [0.+0.j  0.+0.j  0.+0.j  1.+0.5j 0.+0.j  0.+0.j  0.+0.j  0.+0.j ]
 [1.+0.5j 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j ]
 [0.+0.j  1.+0.5j 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j ]
 [0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.5j 0.+0.j ]
 [0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.5j]
 [0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.5j 0.+0.j  0.+0.j  0.+0.j ]
 [0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.5j 0.+0.j  0.+0.j ]]

In [23]:
H = H_c + H_ab + H_bc + H_ac
H

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[ 1.5+0.5j  0. +0.j   1. +0.j   0. +0.j   0. +0.j   0. +0.j   0. +0.j
   0. +0.j ]
 [ 0. +0.j  -0.5+0.5j  2. +0.j   1. +0.j   2. +0.j   0. +0.j   0. +0.j
   0. +0.j ]
 [ 1. +0.j   2. +0.j  -1.5-0.5j  0. +0.j   2. +0.j   0. +0.j   0. +0.j
   0. +0.j ]
 [ 0. +0.j   1. +0.j   0. +0.j   0.5-0.5j  0. +0.j   2. +0.j   2. +0.j
   0. +0.j ]
 [ 0. +0.j   2. +0.j   2. +0.j   0. +0.j   0.5+0.5j  0. +0.j   1. +0.j
   0. +0.j ]
 [ 0. +0.j   0. +0.j   0. +0.j   2. +0.j   0. +0.j  -1.5+0.5j  2. +0.j
   1. +0.j ]
 [ 0. +0.j   0. +0.j   0. +0.j   2. +0.j   1. +0.j   2. +0.j  -0.5-0.5j
   0. +0.j ]
 [ 0. +0.j   0. +0.j   0. +0.j   0. +0.j   0. +0.j   1. +0.j   0. +0.j
   1.5-0.5j]]

In [30]:
H.eigenenergies(sparse=False, sort='low', eigvals=0, tol=0, maxiter=100000)

array([-3.29645113-8.46490499e-02j, -3.29645113+8.46490499e-02j,
       -2.80824809+3.48394493e-17j, -1.15079552-1.24017476e-16j,
        1.53403163+4.85450000e-01j,  1.53403163-4.85450000e-01j,
        3.09729755+1.93704412e-15j,  4.38658504-1.60114977e-15j])

In [29]:
H.groundstate()

((-3.296451128373749-0.08464904985698679j),
 Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
 Qobj data =
 [[-0.1444569 +0.01760814j]
  [-0.42548141+0.12000257j]
  [ 0.70317504+0.j        ]
  [ 0.12144715-0.12127516j]
  [-0.13389994+0.01722557j]
  [ 0.04436427+0.42254462j]
  [-0.03697178-0.2271167j ]
  [-0.00160868-0.08823457j]])

In [32]:
times = np.linspace(0,100,1000)
result = mesolve(H,gs,times,[],[])

In [36]:
result.states[-1]

Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
Qobj data =
[[ 0.0979398 +0.34401849j]
 [-0.20867761+0.28029825j]
 [-0.08239966+0.3466155j ]
 [-0.45682943+0.22451374j]
 [-0.15831233+0.33005353j]
 [-0.25868284+0.06685181j]
 [-0.24856438+0.15907j   ]
 [-0.25353206-0.08464009j]]

In [34]:
a = H.reshape(8,1,8,1)
a

AttributeError: 'Qobj' object has no attribute 'reshape'