In [201]:
import numpy as np
import scipy
import sympy as sp
import matplotlib.pyplot as plt

In [202]:
I = np.array([[1,0],[0,1]])
sx = np.array([[0,1],[1,0]])
sy = np.array([[0,-1j],[1j,0]])
sz = np.array([[1,0],[0,-1]])

sx2 = np.kron(np.kron(I,sx),I)
sz2 = np.kron(np.kron(I,sz),I)

sx_ab = np.kron(np.kron(sx,I),sx)
sy_ab = np.kron(np.kron(sy,I),sy)
sz_ab = np.kron(np.kron(sz,I),sz)

sx_ac = np.kron(np.kron(sx,sx),I)
sy_ac = np.kron(np.kron(sy,sy),I)
sz_ac = np.kron(np.kron(sz,sz),I)

sx_bc = np.kron(np.kron(I,sx),sx)
sy_bc = np.kron(np.kron(I,sy),sy)
sz_bc = np.kron(np.kron(I,sz),sz)


In [203]:
hz = 0.4
hx = 0.6
D = 0.8

In [204]:
H_c = 1j*hz*sz2 + hx*sx2
H_ab = sx_ab + sy_ab + D*sz_ab
H_bc = sx_bc + sy_bc + D*sz_bc
H_ac = sx_ac + sy_ac + D*sz_ac
H_t = H_c + H_ab + H_bc + H_ac

## Ket space

In [205]:
e, psi = np.linalg.eig(H_t)
print(np.round(min(e),4))

(-3.2472-0j)


In [206]:
psi1 = np.round(psi[:,np.argmin(e)].reshape(8,1),4)
psi1

array([[-0.    +0.j    ],
       [ 0.3727-0.3333j],
       [ 0.    -0.j    ],
       [-0.5   -0.j    ],
       [-0.3727+0.3333j],
       [-0.    +0.j    ],
       [ 0.5   +0.j    ],
       [ 0.    -0.j    ]])

In [207]:
p1 = psi[:,0].reshape(8,1)
p2 = psi[:,1].reshape(8,1)

In [208]:
np.conj(p1).T @ p2

array([[-0.05468596+0.00617579j]])

In [209]:
dm_r = np.round(psi1 @ np.conj(psi1).T,4)
dm_r

array([[ 0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ],
       [ 0.    +0.j    ,  0.25  +0.j    ,  0.    +0.j    ,
        -0.1863+0.1666j, -0.25  +0.j    ,  0.    +0.j    ,
         0.1863-0.1666j,  0.    +0.j    ],
       [ 0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ],
       [ 0.    +0.j    , -0.1863-0.1666j,  0.    +0.j    ,
         0.25  +0.j    ,  0.1863+0.1666j,  0.    +0.j    ,
        -0.25  +0.j    ,  0.    +0.j    ],
       [ 0.    +0.j    , -0.25  +0.j    ,  0.    +0.j    ,
         0.1863-0.1666j,  0.25  +0.j    ,  0.    +0.j    ,
        -0.1863+0.1666j,  0.    +0.j    ],
       [ 0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ],
       [ 0.    +0.j    ,  0.1863+0

In [210]:
sigma_z = np.array([[1,0],[0,-1]])
I = np.array([[1,0],[0,1]])
Sminus = np.array([[0,0],[1,0]])

sigma_cz = np.kron(np.kron(I,sigma_z),I)
Sminus_cz = np.kron(np.kron(I,Sminus),I)     
I_cz = np.kron(np.kron(I,I),I)

a = np.conj(psi1).T @ (0.5*(I_cz + sigma_cz)) @ psi1
b = np.conj(psi1).T @ (Sminus_cz) @ psi1

rho_rc = np.round(np.array([[a,b],[np.conj(b),1-a]]).reshape(2,2),4)
rho_rc

array([[ 0.5   +0.j    , -0.3727+0.3333j],
       [-0.3727-0.3333j,  0.5   +0.j    ]])

In [211]:
lmbda, k = np.linalg.eig(rho_rc)
lmbda

array([9.99994180e-01-2.77555756e-17j, 5.82003387e-06+2.77555756e-17j])

In [212]:
k1 = k[:,0].reshape(2,1)
k2 = k[:,1].reshape(2,1)
print(k1,k2)

[[ 0.70710678+0.j        ]
 [-0.52708353-0.47136287j]] [[0.52708353-0.47136287j]
 [0.70710678+0.j        ]]


In [213]:
np.round(lmbda[0]*(k1@np.conj(k1).T) + lmbda[1]*(k2@np.conj(k2).T),5)

array([[ 0.5   -0.j    , -0.3727+0.3333j],
       [-0.3727-0.3333j,  0.5   +0.j    ]])

In [214]:
print(np.round(rho_rc,5) == np.round(lmbda[0]*(k1@np.conj(k1).T) + lmbda[1]*(k2@np.conj(k2).T),5))

[[ True  True]
 [ True  True]]


## Bra space

In [215]:
H_dag = np.conj(H_t).T
f, phi = np.linalg.eig(H_dag)
min(f)

(-3.247213595499959+7.223993960795284e-16j)

In [216]:
phi1 = np.round(phi[:,np.argmin(f)].reshape(8,1),4)
phi1

array([[-0.    -0.j    ],
       [ 0.3727+0.3333j],
       [ 0.    +0.j    ],
       [-0.5   +0.j    ],
       [-0.3727-0.3333j],
       [-0.    -0.j    ],
       [ 0.5   +0.j    ],
       [ 0.    +0.j    ]])

In [217]:
np.conj(phi1).T @ phi1

array([[0.99998836+0.j]])

In [218]:
dm_l = np.round(phi1 @ np.conj(phi1).T,4)
dm_l

array([[ 0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ],
       [ 0.    +0.j    ,  0.25  +0.j    ,  0.    +0.j    ,
        -0.1863-0.1666j, -0.25  +0.j    ,  0.    +0.j    ,
         0.1863+0.1666j,  0.    +0.j    ],
       [ 0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ],
       [ 0.    +0.j    , -0.1863+0.1666j,  0.    +0.j    ,
         0.25  +0.j    ,  0.1863-0.1666j,  0.    +0.j    ,
        -0.25  +0.j    ,  0.    +0.j    ],
       [ 0.    +0.j    , -0.25  +0.j    ,  0.    +0.j    ,
         0.1863+0.1666j,  0.25  +0.j    ,  0.    +0.j    ,
        -0.1863-0.1666j,  0.    +0.j    ],
       [ 0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ,  0.    +0.j    ,
         0.    +0.j    ,  0.    +0.j    ],
       [ 0.    +0.j    ,  0.1863-0

In [219]:
c = np.conj(phi1).T @ (0.5*(I_cz + sigma_cz)) @ phi1
d = np.conj(phi1).T @ (Sminus_cz) @ phi1

rho_lc = np.array([[c,d],[np.conj(d),1-c]]).reshape(2,2)
np.round(rho_lc,5)

array([[ 0.49999+0.j    , -0.3727 -0.3333j],
       [-0.3727 +0.3333j,  0.50001+0.j    ]])

In [220]:
lmbda1, k_tilda = np.linalg.eig(rho_lc)
lmbda1

array([5.81989838e-06-2.77555756e-17j, 9.99994180e-01+2.77555756e-17j])

In [221]:
k_tilda1 = k_tilda[:,0].reshape(2,1)
k_tilda2 = k_tilda[:,1].reshape(2,1)
print(k_tilda1,k_tilda2)

[[0.70711501+0.j        ]
 [0.52707739-0.47135738j]] [[-0.52707739-0.47135738j]
 [ 0.70711501+0.j        ]]


In [222]:
print(np.round(rho_lc,5) == np.round(lmbda1[0]*(k_tilda1@np.conj(k_tilda1).T) + lmbda1[1]*(k_tilda2@np.conj(k_tilda2).T),5))

[[ True  True]
 [ True  True]]


## Verifying Orthonormality

In [223]:
N = np.sqrt((k_tilda2).T @ k2)
N

array([[0.00341176-4.06762797e-15j]])

In [224]:
k1_norm = k1/N
k2_norm = k2/N
k_tilda1_norm = k_tilda1/N
k_tilda2_norm = k_tilda2/N

In [225]:
np.round(np.conj(k_tilda1_norm).T @ k2_norm,5)

array([[64037.80069-0.66661j]])

In [226]:
print(np.round(rho_rc,5) == np.round(rho_lc.T,5))

[[False  True]
 [ True False]]


In [227]:
print(psi1 == np.conj(phi1))

[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]


In [228]:
print(H_t == np.conj(H_dag))

[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]


In [229]:
print(dm_l == np.conj(dm_r))

[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]


In [230]:
np.round((np.conj(phi[:,4].reshape(8,1)).T @ psi[:,7].reshape(8,1)),5)

array([[-0.-0.j]])

## rho_ab

In [231]:
def extract_elements_4(test_rhoB,indices):
    # Create a new 4x4 matrix filled with zeros
    four_by_four = [[ 0 for _ in range(4)] for _ in range(4)]
    # Iterate over the elements of the 4x4 matrix
    for i in range (4):
        for j in range (4):
            row_idx, col_idx = indices[i * 4 + j]
            four_by_four[i][j] = test_rhoB[row_idx][col_idx]
    return four_by_four

In [232]:
list_3c = []
indices = [(0,0),(0,1),(0,4),(0,5),(1,0),(1,1),(1,4),(1,5),(4,0),(4,1),(4,4),(4,5),(5,0),(5,1),(5,4),(5,5)]
four_by_four = extract_elements_4(dm_r,indices)
e =four_by_four
indices = [(2,2),(2,3),(2,6),(2,7),(3,2),(3,3),(3,6),(3,7),(6,2),(6,3),(6,6),(6,7),(7,2),(7,3),(7,6),(7,7)]
four_by_four = extract_elements_4(dm_r,indices)
d =four_by_four
rho_31 = np.add(e,d)
list_3c.append(rho_31)
rho_ab = np.asarray(list_3c).reshape(4,4)
np.round(rho_ab,4)

array([[ 0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j],
       [ 0. +0.j,  0.5+0.j, -0.5+0.j,  0. +0.j],
       [ 0. +0.j, -0.5+0.j,  0.5+0.j,  0. +0.j],
       [ 0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j]])

In [233]:
np.shape(rho_ab)

(4, 4)

In [234]:
lmbda2, k_ab = np.linalg.eig(rho_ab)
lmbda2

array([1.0000000e+00+0.j, 7.2203753e-33+0.j, 0.0000000e+00+0.j,
       0.0000000e+00+0.j])

In [235]:
k_ab1 = k_ab[:,0].reshape(4,1)
k_ab1

array([[ 0.        +0.j],
       [-0.70710678+0.j],
       [ 0.70710678+0.j],
       [ 0.        +0.j]])

In [236]:
rhs = 0
for i in range(len(lmbda2)):
    rhs = rhs + np.round(lmbda2[i]*(k_ab[:,i].reshape(4,1))@np.conj(k_ab[:,i].reshape(4,1)).T,4)
rhs

array([[ 0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j],
       [ 0. +0.j,  0.5+0.j, -0.5+0.j,  0. +0.j],
       [ 0. +0.j, -0.5+0.j,  0.5+0.j,  0. +0.j],
       [ 0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j]])

In [237]:
np.round(np.sqrt(lmbda[0]*lmbda2[0])*np.kron(k1,np.conj(k_ab1)).T,4).reshape(8,1)

array([[ 0.    +0.j    ],
       [-0.5   +0.j    ],
       [ 0.5   -0.j    ],
       [ 0.    +0.j    ],
       [ 0.    +0.j    ],
       [ 0.3727+0.3333j],
       [-0.3727-0.3333j],
       [ 0.    +0.j    ]])

In [238]:
np.round(psi1,4)

array([[-0.    +0.j    ],
       [ 0.3727-0.3333j],
       [ 0.    -0.j    ],
       [-0.5   -0.j    ],
       [-0.3727+0.3333j],
       [-0.    +0.j    ],
       [ 0.5   +0.j    ],
       [ 0.    -0.j    ]])

## my_functions_plot

In [239]:
%run my_functions.ipynb

In [240]:
ket_psi, ket_phi = eigvectors(H_t)

In [241]:
ket_psi

array([[-8.09195593e-17+5.40296317e-17j],
       [ 3.72677996e-01-3.33333333e-01j],
       [ 7.97636480e-16-4.54581745e-16j],
       [-5.00000000e-01-9.15933995e-16j],
       [-3.72677996e-01+3.33333333e-01j],
       [-7.11932716e-16+1.07382294e-15j],
       [ 5.00000000e-01+0.00000000e+00j],
       [ 1.88252145e-16-2.13533254e-16j]])

In [242]:
ket_phi

array([[-8.09195593e-17-5.40296317e-17j],
       [ 3.72677996e-01+3.33333333e-01j],
       [ 7.97636480e-16+4.54581745e-16j],
       [-5.00000000e-01+9.15933995e-16j],
       [-3.72677996e-01-3.33333333e-01j],
       [-7.11932716e-16-1.07382294e-15j],
       [ 5.00000000e-01+0.00000000e+00j],
       [ 1.88252145e-16+2.13533254e-16j]])

In [243]:
rdm_rc, rdm_lc = rho_c(ket_psi,ket_phi)

In [244]:
rdm_lc

array([[ 0.5     +0.j        , -0.372678-0.33333333j],
       [-0.372678+0.33333333j,  0.5     +0.j        ]])

In [245]:
l = np.linalg.eigvals(rdm_rc)
np.round(l,4)

array([0.-0.j, 1.-0.j])

In [246]:
Entropy(rdm_rc)

0.0

In [247]:
Entropy(rdm_lc)

0.0