In [1]:
import numpy as np
from numpy import linalg as LA
from numpy import matrix
%run my_functions.ipynb

## System
###      A------C------B

In [2]:
N = 3 #Number of spins

s1 = np.array([1,0])
s2 = np.array([1,0])
s3 = np.array([1,0])
gs = np.kron(np.kron(s1,s2),s3)

In [3]:
#Pauli matrices
I = np.array([[1,0],[0,1]])
sx = np.array([[0,1],[1,0]])
sy = np.array([[0,-1j],[1j,0]])
sz = np.array([[1,0],[0,-1]])

In [4]:
#hamiltonian for C subsystem
hz = 0.7902020202020202
hx = 0.8
sx2 = np.kron(np.kron(I,sx),I)
sz2 = np.kron(np.kron(I,sz),I)

H_c = 1j*hz*sz2 + hx*sx2

In [5]:
#AB interactions
sx_ab = np.kron(np.kron(sx,I),sx)
sy_ab = np.kron(np.kron(sy,I),sy)
sz_ab = np.kron(np.kron(sz,I),sz)

sx_ac = np.kron(np.kron(sx,sx),I)
sy_ac = np.kron(np.kron(sy,sy),I)
sz_ac = np.kron(np.kron(sz,sz),I)

sx_bc = np.kron(np.kron(I,sx),sx)
sy_bc = np.kron(np.kron(I,sy),sy)
sz_bc = np.kron(np.kron(I,sz),sz)

D = 0.020202020202020204

H_ab = sx_ab + sy_ab + D*sz_ab
H_bc = sx_bc + sy_bc + D*sz_bc
H_ac = sx_ac + sy_ac + D*sz_ac

In [6]:
H = H_c + H_ab + H_bc + H_ac

In [7]:
H_dag = np.matrix.getH(H)

## Left Eigenvectors

In [8]:
p,q = np.linalg.eig(H_dag)
min(p)

(-2.243683136231523+4.871801160328235e-16j)

In [9]:
p_round = np.round(p,3)
p_round

array([ 4.428+0.j   ,  3.505-0.j   ,  0.184-0.751j,  0.184+0.751j,
       -2.244+0.j   , -2.018-0.j   , -2.145+0.j   , -1.895-0.j   ])

In [10]:
q1 = q[:,np.argmin(p)].reshape(8,1)
q1

array([[-0.17061643-0.05850891j],
       [-0.27117697-0.09679875j],
       [ 0.54922932+0.j        ],
       [ 0.15417842+0.24317887j],
       [-0.27117697-0.09679875j],
       [-0.12103382-0.53572723j],
       [ 0.15417842+0.24317887j],
       [ 0.09466933+0.15352842j]])

In [11]:
np.matrix.getH(q1)@q1

array([[1.+0.j]])

In [28]:
q1_dag = np.conj(q1).T
q1_dag

array([[-0.17061643+0.05850891j, -0.27117697+0.09679875j,
         0.54922932-0.j        ,  0.15417842-0.24317887j,
        -0.27117697+0.09679875j, -0.12103382+0.53572723j,
         0.15417842-0.24317887j,  0.09466933-0.15352842j]])

In [14]:
np.shape(q1_dag)

(1, 8)

In [15]:
#Verifying GS eigenenergy and eigenfunction
print(np.round(H_dag@q1,5) == np.round(min(p)*q1,5))

[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]


## Right Eigenvectors

In [16]:
#Eigenvalues of H
w,v = np.linalg.eig(H)
print(min(w)) #Ground state energy

(-2.243683136231523-4.871801160328235e-16j)


In [17]:
w_round = np.round(w,3)
w_round

array([ 4.428-0.j   ,  3.505+0.j   ,  0.184+0.751j,  0.184-0.751j,
       -2.244-0.j   , -2.018+0.j   , -2.145-0.j   , -1.895+0.j   ])

In [18]:
#Ground state
v1 = v[:,np.argmin(w)].reshape(8,1) 
v1

array([[-0.17061643+0.05850891j],
       [-0.27117697+0.09679875j],
       [ 0.54922932+0.j        ],
       [ 0.15417842-0.24317887j],
       [-0.27117697+0.09679875j],
       [-0.12103382+0.53572723j],
       [ 0.15417842-0.24317887j],
       [ 0.09466933-0.15352842j]])

In [19]:
#Verifying GS eigenenergy and eigenfunction
print(np.round(H@v1,5) == np.round(min(w)*v1,5))

[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]


In [20]:
N = np.sqrt(q1_dag@v1)
N

array([[0.52086321-0.41631501j]])

In [34]:
q1_dag_norm = q1_dag/N
q1_dag_norm

array([[-0.25465972-0.0912135j , -0.40831775-0.14051685j,
         0.6434157 +0.51426864j,  0.40831775-0.14051685j,
        -0.40831775-0.14051685j, -0.6434157 +0.51426864j,
         0.40831775-0.14051685j,  0.25465972-0.0912135j ]])

In [35]:
np.conj(q1_dag_norm).T

array([[-0.25465972+0.0912135j ],
       [-0.40831775+0.14051685j],
       [ 0.6434157 -0.51426864j],
       [ 0.40831775+0.14051685j],
       [-0.40831775+0.14051685j],
       [-0.6434157 -0.51426864j],
       [ 0.40831775+0.14051685j],
       [ 0.25465972+0.0912135j ]])

In [32]:
v1_norm = v1/N
v1_norm

array([[-0.25465972-0.0912135j ],
       [-0.40831775-0.14051685j],
       [ 0.6434157 +0.51426864j],
       [ 0.40831775-0.14051685j],
       [-0.40831775-0.14051685j],
       [-0.6434157 +0.51426864j],
       [ 0.40831775-0.14051685j],
       [ 0.25465972-0.0912135j ]])

In [33]:
q1_dag_norm @ v1_norm

array([[1.+4.4408921e-16j]])

## Density Matrix

In [25]:
dm = np.round(v1_norm @ q1_dag_norm,3)
dm

array([[ 0.057+0.046j,  0.091+0.073j, -0.117-0.19j , -0.117-0.001j,
         0.091+0.073j,  0.211-0.072j, -0.117-0.001j, -0.073+0.j   ],
       [ 0.091+0.073j,  0.147+0.115j, -0.19 -0.3j  , -0.186-0.j   ,
         0.147+0.115j,  0.335-0.12j , -0.186-0.j   , -0.117+0.001j],
       [-0.117-0.19j , -0.19 -0.3j  ,  0.15 +0.662j,  0.335+0.12j ,
        -0.19 -0.3j  , -0.678+0.j   ,  0.335+0.12j ,  0.211+0.072j],
       [-0.117-0.001j, -0.186-0.j   ,  0.335+0.12j ,  0.147-0.115j,
        -0.186+0.j   , -0.19 +0.3j  ,  0.147-0.115j,  0.091-0.073j],
       [ 0.091+0.073j,  0.147+0.115j, -0.19 -0.3j  , -0.186+0.j   ,
         0.147+0.115j,  0.335-0.12j , -0.186+0.j   , -0.117+0.001j],
       [ 0.211-0.072j,  0.335-0.12j , -0.678+0.j   , -0.19 +0.3j  ,
         0.335-0.12j ,  0.15 -0.662j, -0.19 +0.3j  , -0.117+0.19j ],
       [-0.117-0.001j, -0.186-0.j   ,  0.335+0.12j ,  0.147-0.115j,
        -0.186+0.j   , -0.19 +0.3j  ,  0.147-0.115j,  0.091-0.073j],
       [-0.073+0.j   , -0.117+0.001j,  0.