In [1]:
import numpy as np
import qutip
from qutip import Qobj
import matplotlib.pyplot as plt
import qiskit
import qiskit.quantum_info as qi
%run my_functions.ipynb

In [2]:
psi = np.array([[ 0.01143251+0.00506275j],
 [-0.43682532+0.02052994j],
 [-0.09293022-0.05482747j],
 [-0.022865  +0.5348183j ],
 [ 0.54494378+0.j        ],
 [ 0.03196246-0.1030557j ],
 [-0.04339499-0.44695084j],
 [-0.00506275+0.01143251j]])

In [3]:
phi = np.array([[ 0.01143251-0.00506275j],
 [-0.43682532-0.02052994j],
 [-0.09293022+0.05482747j],
 [-0.022865  -0.5348183j ],
 [ 0.54494378+0.j        ],
 [ 0.03196246+0.1030557j ],
 [-0.04339499+0.44695084j],
 [-0.00506275-0.01143251j]])

In [15]:
N = np.sqrt(np.conj(phi).T @ psi)
N

array([[0.00011363+0.00021432j]])

## Basis of psi, phi

# A -- B -- C

In [16]:
#Basis of subsystem A
a0 = np.array([1,0]).reshape(2,1)
a1 = np.array([1,1]).reshape(2,1)
a0_tilde = np.array([1,-1]).reshape(2,1)
a1_tilde = np.array([0,1]).reshape(2,1)

#Basis of subsystem B
b0 = np.array([1,1+1j]).reshape(2,1)
b1 = np.array([1-1j,1]).reshape(2,1)
b0_tilde = np.array([-1,1+1j]).reshape(2,1)
b1_tilde = np.array([1-1j,-1]).reshape(2,1)

#Basis of subsystem C
c0 = a0
c1 = a1
c0_tilde = a0_tilde
c1_tilde = a1_tilde

In [17]:
np.conj(b1).T @ b0

array([[2.+2.j]])

In [6]:
ket_a0b0c0 = np.kron(a0,np.kron(b0,c0))
ket_a0b0c1 = np.kron(a0,np.kron(b0,c1))
ket_a0b1c0 = np.kron(a0,np.kron(b1,c0))
ket_a0b1c1 = np.kron(a0,np.kron(b1,c1))
ket_a1b0c0 = np.kron(a1,np.kron(b0,c0))
ket_a1b0c1 = np.kron(a1,np.kron(b0,c1))
ket_a1b1c0 = np.kron(a1,np.kron(b1,c0))
ket_a1b1c1 = np.kron(a1,np.kron(b1,c1))

In [7]:
bra_a0b0c0 = np.kron(a0_tilde,np.kron(b0_tilde,c0_tilde))
bra_a0b0c1 = np.kron(a0_tilde,np.kron(b0_tilde,c1_tilde))
bra_a0b1c0 = np.kron(a0_tilde,np.kron(b1_tilde,c0_tilde))
bra_a0b1c1 = np.kron(a0_tilde,np.kron(b1_tilde,c1_tilde))
bra_a1b0c0 = np.kron(a1_tilde,np.kron(b0_tilde,c0_tilde))
bra_a1b0c1 = np.kron(a1_tilde,np.kron(b0_tilde,c1_tilde))
bra_a1b1c0 = np.kron(a1_tilde,np.kron(b1_tilde,c0_tilde))
bra_a1b1c1 = np.kron(a1_tilde,np.kron(b1_tilde,c1_tilde))

In [8]:
N = np.sqrt(np.conj(phi).T @ psi)
dm1 = (psi/N) @ ((np.conj(phi).T)/N)
N

array([[0.00011363+0.00021432j]])

In [9]:
p = 0.5*((np.conj(bra_a0b0c0).T @ dm1 @ ket_a0b0c0) + (np.conj(bra_a0b0c1).T @ dm1 @ ket_a0b0c1) 
    + (np.conj(bra_a1b0c0).T @ dm1 @ ket_a1b0c0) + (np.conj(bra_a1b0c1).T @ dm1 @ ket_a1b0c1))
s = 0.5*((np.conj(bra_a0b1c0).T @ dm1 @ ket_a0b1c0) + (np.conj(bra_a0b1c1).T @ dm1 @ ket_a0b1c1) 
    + (np.conj(bra_a1b1c0).T @ dm1 @ ket_a1b1c0) + (np.conj(bra_a1b1c1).T @ dm1 @ ket_a1b1c1))
q = 0.5*((np.conj(bra_a0b0c0).T @ dm1 @ ket_a0b1c0) + (np.conj(bra_a0b0c1).T @ dm1 @ ket_a0b1c1) 
    + (np.conj(bra_a1b0c0).T @ dm1 @ ket_a1b1c0) + (np.conj(bra_a1b0c1).T @ dm1 @ ket_a1b1c1))
r = 0.5*((np.conj(bra_a0b1c0).T @ dm1 @ ket_a0b0c0) + (np.conj(bra_a0b1c1).T @ dm1 @ ket_a0b0c1) 
    + (np.conj(bra_a1b1c0).T @ dm1 @ ket_a1b0c0) + (np.conj(bra_a1b1c1).T @ dm1 @ ket_a1b0c1))

In [10]:
rho_c = np.array([[p,q],[r,s]]).reshape(2,2)
rho_c

array([[ 12251278.20693592+16221763.5147732j ,
         19534080.47441265 +5626644.03765701j],
       [   -67964.25668481-20328177.58598011j,
        -12251277.70693591-16221763.5147732j ]])

In [11]:
np.linalg.eigvals(rho_c)

array([0.45570719-0.14099544j, 0.04429281+0.14099544j])

In [12]:
Entropy(rho_c)

(0.9274571843729243+0.3547012437786656j)

In [13]:
a = 0.5*((np.conj(bra_a0b0c0).T @ dm1 @ ket_a0b0c0) + (np.conj(bra_a0b0c1).T @ dm1 @ ket_a0b0c1) 
    + (np.conj(bra_a0b1c0).T @ dm1 @ ket_a0b1c0) + (np.conj(bra_a0b1c1).T @ dm1 @ ket_a0b1c1))
b = 0.5*((np.conj(bra_a0b0c0).T @ dm1 @ ket_a1b0c0) + (np.conj(bra_a0b0c1).T @ dm1 @ ket_a1b0c1) 
    + (np.conj(bra_a0b1c0).T @ dm1 @ ket_a1b1c0) + (np.conj(bra_a0b1c1).T @ dm1 @ ket_a1b1c1))
c = 0.5*((np.conj(bra_a1b0c0).T @ dm1 @ ket_a0b0c0) + (np.conj(bra_a1b0c1).T @ dm1 @ ket_a0b0c1) 
    + (np.conj(bra_a1b1c0).T @ dm1 @ ket_a0b1c0) + (np.conj(bra_a1b1c1).T @ dm1 @ ket_a0b1c1))
d = 0.5*((np.conj(bra_a1b0c0).T @ dm1 @ ket_a1b0c0) + (np.conj(bra_a1b0c1).T @ dm1 @ ket_a1b0c1) 
    + (np.conj(bra_a1b1c0).T @ dm1 @ ket_a1b1c0) + (np.conj(bra_a1b1c1).T @ dm1 @ ket_a1b1c1))
rho_a = np.array([[a,b],[c,d]]).reshape(2,2)
rho_a

array([[-581063.77725043 +982095.46773146j,
         401031.44048102+1563159.49498189j],
       [ 781579.74749094 -200515.72024051j,
         581064.27725044 -982095.46773146j]])

In [14]:
np.linalg.eigvals(rho_a)

array([0.2168616+0.08431911j, 0.2831384-0.08431911j])