In [29]:
import numpy as np
import qiskit
from qiskit.quantum_info import DensityMatrix, partial_trace

In [103]:
v1 = [-3.59599360e-17+1.94887014e-17j, -4.33012702e-01+2.50000000e-01j,
  1.84726313e-16-7.68525479e-17j,  5.00000000e-01+0.00000000e+00j,
  4.33012702e-01-2.50000000e-01j, -7.13213118e-16+6.62531315e-16j,
 -5.00000000e-01-4.57966998e-16j,  2.70617559e-16-1.34184989e-16j]

In [69]:
rho_ = np.outer(v1,np.conj(v1))
rho_

array([[ 1.67292648e-33+0.00000000e+00j,  2.04432844e-17+5.51128748e-19j,
        -8.14050275e-33+8.36463251e-34j, -1.79799680e-17+9.74435070e-18j,
        -2.04432844e-17-5.51128748e-19j,  3.85589730e-32+9.92498619e-33j,
         1.79799680e-17-9.74435070e-18j, -1.23464813e-32+4.48701184e-34j],
       [ 2.04432844e-17-5.51128748e-19j,  2.50000000e-01+0.00000000e+00j,
        -9.92019769e-17+1.29034488e-17j, -2.16506351e-01+1.25000000e-01j,
        -2.50000000e-01+0.00000000e+00j,  4.74463168e-16+1.08581195e-16j,
         2.16506351e-01-1.25000000e-01j, -1.50727088e-16+9.55058510e-18j],
       [-8.14050275e-33-8.36463251e-34j, -9.92019769e-17-1.29034488e-17j,
         4.00301248e-32+0.00000000e+00j,  9.23631565e-17-3.84262739e-17j,
         9.92019769e-17+1.29034488e-17j, -1.82666449e-31-6.75747218e-32j,
        -9.23631565e-17+3.84262740e-17j,  6.03026422e-32+3.98984936e-33j],
       [-1.79799680e-17-9.74435070e-18j, -2.16506351e-01-1.25000000e-01j,
         9.23631565e-17+3.84262739e

## Reduced Density matrix of A

In [85]:
rho_ac = partial_trace(rho_,[2])
rho_a = partial_trace(PT_ac,[1])
rho_a

DensityMatrix([[ 5.00000000e-01+0.00000000e+00j,
                -4.96965507e-16-2.13548835e-16j],
               [-4.96965507e-16+2.13548835e-16j,
                 5.00000000e-01+0.00000000e+00j]],
              dims=(2,))


In [89]:
sigma_z = np.array([[1,0],[0,-1]])
I = np.array([[1,0],[0,1]])
Sminus = np.array([[0,0],[1,0]])

sigma_az = np.kron(np.kron(sigma_z,I),I)
I_az = np.kron(np.kron(I,I),I)
Sminus_az = np.kron(np.kron(Sminus,I),I)

In [87]:
sigma_az

array([[ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1]])

In [88]:
a = 0.5*(np.inner(np.conj(v1).T, np.matmul(I_az+sigma_az,v1)))
a

(0.5000000000933409+0j)

In [94]:
M = np.matmul(Sminus_az,sigma_az)
#b = 0.5*(np.inner(np.conj(v1).T, np.matmul(Sminus_az+M,v1)))
b = np.inner(np.conj(v1).T,np.matmul(Sminus_az,v1))
b

(4.969655066759178e-16+2.1354883506944846e-16j)

## Reduced density matrix of C

In [97]:
sigma_cz = np.kron(np.kron(I,sigma_z),I)
Sminus_cz = np.kron(np.kron(I,Sminus),I)
I_cz = I_az

In [96]:
p = 0.5*(np.inner(np.conj(v1).T, np.matmul(I_az+sigma_cz,v1)))
p

(0.5000000001866817+0j)

In [98]:
q = np.inner(np.conj(v1).T, np.matmul(Sminus_cz,v1))
q

(-0.4330127019999999+0.2500000000000002j)

In [99]:
rho_c = np.array([[p,q],[np.conj(q),1-p]])
rho_c

array([[ 0.5      +0.j  , -0.4330127+0.25j],
       [-0.4330127-0.25j,  0.5      +0.j  ]])

In [105]:
#Function
def rho_c(psi):
    sigma_z = np.array([[1,0],[0,-1]])
    I = np.array([[1,0],[0,1]])
    Sminus = np.array([[0,0],[1,0]])
    sigma_cz = np.kron(np.kron(I,sigma_z),I)
    Sminus_cz = np.kron(np.kron(I,Sminus),I)
    I_cz = np.kron(np.kron(I,I),I)
    a = 0.5*(np.inner(np.conj(v1).T, np.matmul(I_cz+sigma_cz,v1)))
    b = np.inner(np.conj(v1).T, np.matmul(Sminus_cz,v1))
    return np.array([[a,b],[np.conj(b),1-a]])

In [104]:
rho_c(v1)

array([[ 0.5      +0.j  , -0.4330127+0.25j],
       [-0.4330127-0.25j,  0.5      +0.j  ]])